docker-compose-yaml: ./lagoon-docker-compose.yml

project: ft-dev-polydoc-engine


tasks:
  post-rollout:
    - run:
        name: Prepare storage
        command: mkdir -p /app/storage/framework/sessions /app/storage/framework/views /app/storage/framework/cache /app/storage/framework/cache/data
        service: cli
        shell: bash
    - run:
        name: Run migrations
        command: php artisan -n migrate --force
        service: cli
        shell: bash
    - run:
        name: Clear caches
        command: php artisan -n optimize:clear
        service: cli
        shell: bash
    - run:
        name: Build caches when pushing to production
        when: LAGOON_ENVIRONMENT_TYPE == "production"
        command: php artisan optimize
        service: cli
        shell: bash

backup-schedule:
  production: "M * * * *"

environments:
  main:
    cronjobs:
      - name: Horizon Radiator
        schedule: "*/3 * * * *"
        command: /app/lagoon/workers/status-horizon.sh
        service: worker
